name = "medquiz"
compatibility_date = "2024-11-17"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production]
name = "medquiz"
compatibility_flags = ["nodejs_compat"]

[[env.production.d1_databases]]
binding = "DB"
database_name = "medquiz-db"
database_id = "6a37a0cd-06cc-4a52-b4af-e831666e3ee5"

[env.production.vars]
NODE_ENV = "production"

